[package]
name = "metadata_extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
kamadak-exif = "0.5.5"
wasm-bindgen = "0.2.83"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"

[lib]
name= "metadata_extractor"
path = "src/lib.rs"
crate-type = ["cdylib"]